### ISSUE TITLE
Use Admin model name instead of Administrator

### ISSUE THREAD

**Issue by ognevsky** [blueberryapps/blueberry_rails#32]
Ahoj, kdyby nekdo mel cas, neni to lepsi mit `Admin` misto `Administrator`? Neboli vam pak prsty? 
/cc @Ceda @atomn @janmarsicek @mbendik

**Comment by Ceda** [comment]
Nene neboli my kopirujem :D :D

**Comment by Ceda** [comment]
Magic rozhodnul ze ne!

**Comment by ognevsky** [comment]
Magic mi pak zaplati za kazdej `istrator` co napisu 😈
